### PR TITLE
Add API version configuration

### PR DESCRIPTION
**Pull request by xtuc**
Fix issue https://github.com/gwkunze/dynamo-session-bundle/issues/8

### CODE REVIEW

**Comment by edummer** [comment]
@gwkunze Could you please merge this pull request.  I could really use your bundle, but I'm using v3 and don't really want to fork for such a trivial change.

Thank you in advance.
--Eric

**Comment by xtuc** [comment]
@edummer You can temporary use my fork https://github.com/xtuc/dynamo-session-bundle. You can set custom git repository as a dependency with composer (https://getcomposer.org/doc/05-repositories.md#using-private-repositories).

**Comment by okdewit** [comment]
@xtuc Personally, I had to edit a few more things to get it to work, as the AWS config needs to be in the form:

    aws:
        version: latest
        region: eu-central-1
        credentials:
            key: <key>
            secret: <secret>

And the session handler methods are slightly different as well.

See:  https://github.com/okdewit/dynamo-session-bundle
This breaks backwards compatibility with AWS SDK v2 though, unless it was rewritten to recognize the installed SDK version and use the appropriate config/methods.

**Comment by gwkunze** [comment]
Sorry for leaving this PR open for so long, I've merged it together with #10.

**Pull request merged**
