### PR TITLE
Added Definition::setFactory usage to be symfony v3 compatible

### PR DESCRIPTION
**Pull request by aklinkert**

### CODE REVIEW

**Comment by apinnecke** [comment]
@gwkunze Any chance to get this merges after two and a half months?

**Comment by piotrbelina** [comment]
+1

**Comment by pleone** [comment]
@gwkunze any updates?
 @apinnecke 's would make this package symfony3 ready

**Comment by sorpion** [comment]
+1

**Comment by gwkunze** [comment]
Apologies for the very late merge.

**Pull request merged**
